name: Build and Test for Red Hat 9

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [redhat9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker://multiarch/qemu-user-static
      with:
        args: --reset -p yes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64 --tag myimage .

    - name: Test Docker image
      run: |
        docker run --rm myimage /path/to/test/script.sh
